### ISSUE TITLE
run 您的项目 失败了。将错误信息发您邮箱了。期待恢复啊。

### ISSUE THREAD

**Issue by Xrq1995** [itcastWsy/wx_baidu#1]
18756133290@163.com

**Comment by itcastWsy** [comment]
![image](https://user-images.githubusercontent.com/33108189/39339186-eb8bc2c0-49f9-11e8-8c25-4aa24cbfc475.png)
这个fff 是在微信代码里面定义的属性名，后台通过这个fff字段获取到对应的录音文件。  你也可以自己重命名
